branch-defaults:
  master:
    environment: printachu-dev
    group_suffix: null
environment-defaults:
  printachu-dev:
    branch: null
    repository: null
global:
  application_name: printachu-eb
  branch: null
  default_ec2_keyname: printachu
  default_platform: Python 2.7
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
