# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
