# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_auto_20170405_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
