# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20170405_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
