# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poster', '0005_artistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curr_status', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='Description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='cash_nrec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='cash_rec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='designs_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=b''),
        ),
    ]
