# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 00:50
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_auto_20170506_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
