# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0008_auto_20170511_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=b''),
        ),
    ]
