# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
