# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0013_poster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
