# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0017_auto_20170525_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='poster',
            name='quora_count',
            field=models.IntegerField(default=0),
        ),
    ]
