# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0018_auto_20170525_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='poster_name',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='tags',
            name='title',
            field=models.CharField(default='anything', max_length=100),
        ),
    ]
