# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0019_auto_20170528_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='poster_name',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
