# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0021_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='background_pic',
            field=models.ImageField(default='', upload_to=b''),
        ),
    ]
