# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0022_artistprofile_background_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='cart',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='cart',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
