# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0024_auto_20170727_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='about',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
