# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0026_auto_20170728_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
