# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0027_auto_20170729_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
